# Generated by Django 5.2.5 on 2026-06-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seller_agreed_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='buyer_agreed_terms',
            field=models.BooleanField(default=False),
        ),
    ]
