# Generated by Django 5.2.5 on 2026-06-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_usercomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplaint',
            name='complaint_type',
            field=models.CharField(choices=[('technical_issue', 'Technical Issue'), ('account_problem', 'Account Problem'), ('inappropriate_content', 'Inappropriate Content'), ('harassment', 'Harassment'), ('spam', 'Spam'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
