# Generated by Django 5.2.5 on 2026-05-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_college_representative',
            field=models.BooleanField(default=False),
        ),
    ]
