# Generated by Django 5.2.5 on 2026-06-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_college_customuser_is_college_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='college_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_college_verified',
            field=models.BooleanField(default=False),
        ),
    ]
