# Generated by Django 5.2.5 on 2026-06-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('purchase_request', 'Purchase Request'), ('purchase_approved', 'Purchase Approved'), ('purchase_rejected', 'Purchase Rejected'), ('representative_approved', 'Representative Access Approved'), ('representative_rejected', 'Representative Access Rejected'), ('like', 'Post Liked'), ('comment', 'Post Commented'), ('other', 'Other')], max_length=30),
        ),
    ]
